### ISSUE TITLE
zsh: command not found: trash

### ISSUE THREAD

**Issue by shaktiness** [sindresorhus/trash#103]
I'm getting this error, i've tried installing this several ways.  Sry I'm a newb.  There is a huge laundry list when I try to install but the few first are: 

$ npm install trash
npm install trash deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
........

npm WARN chris@1.0.0 No description
npm WARN chris@1.0.0 No repository field.

+ trash@6.1.1
updated 1 package and audited 310 packages in 8.606s

2 packages are looking for funding
  run `npm fund` for details

**Comment by sindresorhus** [comment]
It's `trash-cli`, not `trash`.

**Comment by shaktiness** [comment]
Thank you. I tried that also, and:
$ npm install --global trash-cli
$ npm install trash-cli

It still give me this:
$ npm install --global trash-cli
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/Users/chris/.npm-global/bin/trash -> /Users/chris/.npm-global/lib/node_modules/trash-cli/cli.js
+ trash-cli@3.1.0
updated 1 package in 11.807s
