### ISSUE TITLE
feat: read the recycle bin/trash folder

### ISSUE THREAD

**Issue by kimlimjustin** [sindresorhus/trash#117]
Firstly, thanks for your hard work for this awesome project. However, it seems that this project only provides a function to move file(s) into recycle bin/trash. Could you please also add the feature to read the recycle bin/trash and return an array of the file path and/or its information such as time deleted, etc? I can help with the Linux part if you want to.

**Comment by sindresorhus** [comment]
I'm unfortunately not interested in adding that. Very few actually need to get the contents of the trash, so I prefer to keep my package focused on the 95% use-case.
