### ISSUE TITLE
Possible to optionally disable sound effect?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/trash#18]
I'm using this in a build script on OSX and the paper crumple sound is a little off-putting. I like using the trash bin for speed and recovery, but would prefer to keep this functionality completely invisible.

**Comment by Niels-NTG** [comment]
Personally I don't mind the sound-effect that much. It gives some satisfying feedback.

Perhaps it could be a good idea to build in a option like -m (m = mute) to not play the sound when trashing something.

**Comment by kevva** [comment]
If it was easy to remove the sound, we would do it.

**Comment by sindresorhus** [comment]
Fixed it by writing a binary in Objective-C that trashes the files.

Added bonus is that trashing on OS X should be a lot faster now.

https://github.com/sindresorhus/osx-trash

**Comment by stevenvachon** [comment]
Awesome! Thanks @sindresorhus
