### ISSUE TITLE
Lose focus on Windows

### ISSUE THREAD

**Issue by roose** [sindresorhus/trash#22]
Active cmd lose focus on short time, is unpleasantly on Quake mode in ConEmu, maybe use kizzx2's [cmd-recycle](https://github.com/kizzx2/cmd-recycle/downloads)?

**Comment by sindresorhus** [comment]
Yup, but you get focus back immediately, so I don't see it as a severe issue, but yes, would be nice to get fixed. `cmd-recycle` is a no-go as it requires .NET, but I'm working on a solution for this and #16.

**Comment by roose** [comment]
ok, just on Quake mode it's hide ConEmu and show again, not severe issue but unpleasantly :-)

**Comment by b-long** [comment]
:+1: Definitely want to see this implemented for if/when I'm stuck on Windows :D Great work as always @sindresorhus !

**Comment by sindresorhus** [comment]
Should be fixed in latest version of [trash-cli](https://github.com/sindresorhus/trash-cli).
