### ISSUE TITLE
Mention that Ubuntu server doesn't have .local folder?

### ISSUE THREAD

**Issue by bitinn** [sindresorhus/trash#25]
I am not sure this is by design, but Ubuntu Server doesn't have `.local` or its Trash folder by default, how does xdg work in those cases?

I am getting this error:

```
> find ./cache/ -maxdepth 1 -type f -mtime +7 -not -name .gitignore -exec trash {} + && empty-trash

ENOENT: no such file or directory, scandir '/home/dev/.local/share/Trash/files'
```

**Comment by bitinn** [comment]
I just happen to use it to clear up cache folder through npm command, back to `rm`?

**Comment by sindresorhus** [comment]
Yeah, looks like a bug. Can you open the issue here instead https://github.com/kevva/xdg-trash/issues/new ?
