### ISSUE TITLE
Don't error on missing files

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/trash#26]
I don't think it should error when the files you specified doesn't exists. It should log it, but exit with error code `0`. Currently you have to use `trash --force` if you want to use it for cleaning up a build dist dir or something, as the directory might not exists.

So need to differentiate between missing files and actual errors. Should be easy. Just use [`path-exists`](https://github.com/sindresorhus/path-exists) on them. I know this is a race condition, but shouldn't matter and probably easier than checking afterwards.

Thoughts?

-

//@kevva @arthurvr

**Comment by arthurvr** [comment]
> It should log it, but exit with error code 0.

:+1:

**Comment by kevva** [comment]
Only in the CLI?

**Comment by sindresorhus** [comment]
Yes
