### ISSUE TITLE
npm install errors out

### ISSUE THREAD

**Issue by jhendley25** [sindresorhus/trash#30]
Attached is a screenshot.
![screen shot 2015-08-04 at 1 26 12 pm](https://cloud.githubusercontent.com/assets/5239363/9067622/8733f09a-3aac-11e5-8ddb-ee0e82a81bd1.png)

**Comment by sindresorhus** [comment]
Upgrade npm.

**Comment by jhendley25** [comment]
My bad, should have thought of that.
![b2b8f8441aa4811dcac169a9a5daba7e618b089a3271e525711cc4bcf95d891e](https://cloud.githubusercontent.com/assets/5239363/9069814/9b478e86-3ab9-11e5-8f1b-5ad216a74fdf.jpg)
