### ISSUE TITLE
Failure during installation of trash

### ISSUE THREAD

**Issue by dimchez** [sindresorhus/trash#31]
I'm having strange troubles with installing trash via npm

```
npm i trash -D
```

fails with the following output on the console

```
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "trash" "-D"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Invalid name: "@sindresorhus/df"
```

I suppose that might be caused by failing to install https://github.com/sindresorhus/df I've tried installing that package directly and it fails with the same error.

Any hints on what might be causing this issue?

**Comment by kevva** [comment]
Hmm, I don't know if npm 2.10.1 supports scoped packages. Could you try upgrading npm and test again?

**Comment by dimchez** [comment]
@kevva It worked after I've updated to npm 2.13.3 Thanks!
