### ISSUE TITLE
Add glob support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/trash#38]
Using [globby.sync()](https://github.com/sindresorhus/globby).

- [ ] Add it
- [ ] Update usage example in readme
- [ ] Update `trash-cli` readme

PR welcome :)

**Comment by sotojuan** [comment]
Would this just be like in del and use globby? If so I can give it a try!

**Comment by sotojuan** [comment]
Question: Should the glob support be automatic or should the user supply an option? I got it working, but it doesn't match `'weird\\\\name\\"\''`  because of the `/`s. It makes globby think it's a directory listing. Since it doesn't find one, it doesn't delete the file.

**Comment by sotojuan** [comment]
Sorry if you're busy Sindre, but let me know what you think of this ~_~ The "weird name" test is the only issue, assuming automatic globbing.

**Comment by sindresorhus** [comment]
Yes, should be just automatic. To fix the mentioned problem we should set `nonull: true` in `globby`.

https://github.com/isaacs/node-glob#comparisons-to-other-fnmatchglob-implementations

**Comment by sotojuan** [comment]
Thanks. Expect a PR soon!

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/trash/commit/ccd8d52d14f4f4b930e494d3909ffe26cb6fe1cb.
