### ISSUE TITLE
Invalid name: "@sindresorhus/df" trying to install on OSX.

### ISSUE THREAD

**Issue by matiu** [sindresorhus/trash#49]
```
$ npm install  trash
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "trash"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! Invalid name: "@sindresorhus/df"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ematiu/devel/kk/npm-debug.log
```

**Comment by SamVerschueren** [comment]
Works fine here. Could you try again, maybe a `npm` hick up or something.

**Comment by matiu** [comment]
This is related to https://github.com/kevva/xdg-trashdir/blob/master/package.json#L30

**Comment by sindresorhus** [comment]
Either an issue with your system or npm. Use  https://github.com/npm/npm/issuesfor npm support.

**Comment by SamVerschueren** [comment]
I know this is related to that line, but as you can see, the [@sindresorhus/df](https://www.npmjs.com/package/@sindresorhus/df) package is published on npm. This is definitely an issue with `npm` as you can find dozens of those issues when googling.

**Comment by matiu** [comment]
thanks. upgrading to npm 3 fixed the issue. (npm install -g npm@latest)
