### ISSUE TITLE
Hangs when trying to trash a fifo file

### ISSUE THREAD

**Issue by eush77** [sindresorhus/trash#50]
On my Linux box, the following gets `trash` stuck:

```
$ mkfifo a.fifo
$ trash a.fifo
# (hangs)
```

The trace leads to [mount-point](https://github.com/kevva/mount-point/blob/v1.2.0/index.js#L6) and [`@sindresorhus/df`](https://github.com/sindresorhus/df/blob/1.0.1/index.js#L5), which spawn a `df` process which tries to `open()` a fifo file which gets blocked until the other end opens it first. Reported upstream: https://github.com/kevva/mount-point/issues/4.

**Comment by kevva** [comment]
https://github.com/kevva/mount-point/issues/4#issuecomment-528819467
