### ISSUE TITLE
permission error, trying to create .Trash folder in the root of the partition (Linux)

### ISSUE THREAD

**Issue by jhidding** [sindresorhus/trash#51]
Hi, In my setup my homedirectory is on a different partition than the working directory. `trash` tries to create `.Trash-1000` in mount-point of the partition that I'm working on, but user 1000 has no permissions there, giving me

> Error: EACCES: permission denied, mkdir '/mnt/Knolselderij/.Trash-1000'

**Comment by sindresorhus** [comment]
It should follow the XDG Trash spec: https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html I don't really have time to check who's correct, but help welcome.

**Comment by jhnstrk** [comment]
This falls into the following case in the spec:

> If both (1) and (2) fail (that is, no $topdir/.Trash directory exists, and an attempt to create $topdir/.Trash-$uid fails), the implementation MUST either trash the file into the user's “home trash” or refuse to trash it. The choice between these options can be pre-determined, or it can depend on the particular situation (for example, “no trashing of very large files”). However, if an implementation refuses to trash a file after a user action that generally causes trashing, it MUST clearly warn the user that the trashing has failed. It MUST NOT erase the file without user confirmation.

Trash is behaving in an ugly, but specification-conforming, manner by failing and refusing to trash the file(s). It could also move the files to the user's home Trash folder, but this risks filling up the home partition, Neither approach will suit everyone.

**Comment by sindresorhus** [comment]
@jhnstrk Thanks for looking into this :)

**Comment by sindresorhus** [comment]
Closing as it's conforming to spec. If the behavior is sub-optimal, I recommend taking it up with the spec authors.
