### ISSUE TITLE
Trash messes up process.cwd

### ISSUE THREAD

**Issue by NeekSandhu** [sindresorhus/trash#58]
**Affected operating systems:** Mac, Linux
(Windows locks an open path, so isn't affected)

**Expected behaviour:** `process.cwd()` must return the real value of `cwd` at the time it's called

**Current behaviour:** `process.cwd()` returns the initial value of `cwd`, the one where node app got started

**Test case:** https://www.dropbox.com/sh/5cai7qyyqq5ip9x/AABMIaXA_170qvfFgTdkx0Sca?dl=0

- Download the `app` folder
- `cd` into `app` folder
- `npm install`
- `node app`

**Comment by sindresorhus** [comment]
Trash doesn't touch or cache `process.cwd()`. You also do some weird stuff by comparing the function `process.cwd` (not the returned value) against itself, in your test case. I don't understand what your test case is proving, but happy to take another look if you submit an actual [failing test](https://github.com/avajs/ava#failing-tests).

**Comment by NeekSandhu** [comment]
Sorry I tried to prepare an `ava` test but couldn't. So I'd love if you can spare me for that.

Speaking of comparing function refs, I ran the same script file with `require('trash')` replaced with `require('chalk')` and some others, and function refs didn't change.

So essentially the test case proves that the real `process.cwd()` isn't up-to-date with actual value but it's reference `const cwd` is.

For example: If the path to `app.js` before running it is `/xyz/app/app.js` and at runtime you perform a `rename` such that it changes to `/xyz/app-renamed/app.js` what do you expect `process.cwd()` to return? the former or latter?

The latter of course, but it returns the former instead.

**Comment by sindresorhus** [comment]
Sorry, not much I can do until you can provide a minimal test-case that reproduces the issue.

**Comment by mofux** [comment]
Actually, there is one place in trash that changes the `cwd`: https://github.com/sindresorhus/trash/blob/master/test.js#L10. But it only happens if the `test.js` file is called (e.g. when running `npm test` in that directory)...

**Comment by NeekSandhu** [comment]
I explored this further and can say it's not trash, I tried more packages and some of them show same problem (although not saying they cause it). It might be nodejs runtime, it could be something else.
