### ISSUE TITLE
Add ability to disable glob matching

### ISSUE THREAD

**Issue by mofux** [sindresorhus/trash#60]
I already know the files or folders I want to delete, so I simply pass them to trash in an array. Fine. Now consider this:

```bash
touch "test*.txt"
touch test1.txt
touch test2.txt
touch test3.txt
```

And guess what happens if I tell trash to remove the regular file "test*.txt", not good 😅
```javascript
trash(['test*.txt'])
```

Therefore I would opt for an option that disables the globber and simply uses the file list I pass.
I'd like to create a PR if you're willing to accept. I propose an interface like this:

```javascript
trash(['test*.txt'], { glob: false })
```

**Comment by sindresorhus** [comment]
Sure

**Comment by kevva** [comment]
You can escape the character like this `trash(['test\\*.txt'])`, which imo is a better choice than adding a new option.

**Comment by mofux** [comment]
@kevva If it was only for the`*` I would agree, but there are so many special characters in a glob pattern `*`, `(`, `)`, `?`, `!`, `+`, `@` that it would just feel strange and leave me with a somewhat bad feeling if I did escape them. In the end, this lib is about deleting files - which is the one most sensitive system action that you don't want to mess up 😅.

**Comment by sindresorhus** [comment]
@kevva I could think of a different use-case. When you've already globbed or gotten the list of files using another mechanism and then pass it to `trash`, it could be helpful to disable globbing for performance reasons.
