### ISSUE TITLE
Broken symlinks are silently ignored

### ISSUE THREAD

**Issue by jdanford** [sindresorhus/trash#63]
As the title says, the `trash` function silently ignores broken symlinks (because `fs.existsSync` returns false), whereas https://github.com/sindresorhus/macos-trash handles them as expected, i.e.  moving them to the Trash. Is the former behavior intentional?

**Comment by sindresorhus** [comment]
I don't remember exactly why we're doing it in the first place, but I think it's so not to error on non-existing paths. Relevant commit: https://github.com/sindresorhus/trash/commit/34e4d71f7779f2b5406eb3e0b20cd5ea5ebed149

I guess we could use `fs.lstatSync()` instead to support broken symlinks.

**Comment by jdanford** [comment]
That's what I was thinking – should I go ahead and submit a PR?

**Comment by sindresorhus** [comment]
Yes :)
