### ISSUE TITLE
fs.lstatSync throws when file doesn't exist.

### ISSUE THREAD

**Issue by jdalton** [sindresorhus/trash#66]
With the addition of using `fs.lstatSync` 
https://github.com/sindresorhus/trash/commit/126a1dd1532d0bdd236628fb8db505db033d9273, now `trash` errors with
 ```
Error: ENOENT: no such file or directory, lstat './the-file'
    at Object.fs.lstatSync 
```
When a file doesn't exist, where as `fs.existsSync` would return `false`.

Related to #64 *(\cc @jdanford)*

**Comment by jdalton** [comment]
\cc @jdanford

**Comment by jdanford** [comment]
Wow, I should have caught that – thank you!

**Comment by jdalton** [comment]
@jdanford Np. Is this symlink issue of `fs.existsSync` known by Node? It may be something to raise an issue with on the Node tracker as well to see if they can fix the behavior at the core level.

**Comment by jdanford** [comment]
Many file-related functions transparently follow symlinks, in accordance with the behavior of [`stat()`](http://man7.org/linux/man-pages/man2/stat.2.html#DESCRIPTION) in POSIX, so `fs.existsSync()` is doing the right thing here. More importantly, `fs.exists()` and its synchronous counterpart [are now deprecated](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) in favor of using `fs.stat()` directly, so either way there's no issue!

**Comment by jdalton** [comment]
`fs.existsSync` is not deprecated, only `fs.exists`.

**Comment by jdanford** [comment]
My mistake!
