### ISSUE TITLE
Provide TypeScript typings

### ISSUE THREAD

**Issue by matthew-matvei** [sindresorhus/trash#68]
I'm happy to share my simple `.d.ts` file that I've put together to get `trash` working in my TypeScript project. Given that this involve a bit of `npm` package configuration, I won't go so far as to make a full pull request.

`.../trash/index.d.ts`
```typescript
declare module "trash" {

    interface TrashOptions {
        glob: boolean;
    }

    function trash(iterable: Iterable<string>, opts?: TrashOptions);

    export = trash;
}

```

**Comment by sindresorhus** [comment]
Thanks, I'm not using TypeScript personally, so I'm not interested or able to maintain type definitions for it. Would be better to submit to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead.

See: https://github.com/sindresorhus/ama/issues/439

**Comment by matthew-matvei** [comment]
Fair enough. Will do

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
