### ISSUE TITLE
Upgrade fs-extra dep

### ISSUE THREAD

**Issue by jdalton** [sindresorhus/trash#71]
The current dep of `fs-extra` is pretty old and contains a now deprecated `Buffer` usage. This will turn into a runtime error in Node v10.

**Comment by sindresorhus** [comment]
I tried, but tests were failing and I don't have a Linux machine or time to debug.

https://travis-ci.org/sindresorhus/trash/builds/358470595

**Comment by jdalton** [comment]
Hmm interesting. Thanks for attempting it. I'll check it out.

**Comment by sindresorhus** [comment]
Closing as we're no longer using `fs-extras`.

**Comment by jdalton** [comment]
Thank you @sindresorhus!
