### ISSUE TITLE
Keep getting this error when running Trash:  The fs.promises API is experimental

### ISSUE THREAD

**Issue by ryancraigmartin** [sindresorhus/trash#72]
The command still runs, but this message pops up every time. 

`(node:3890) ExperimentalWarning: The fs.promises API is experimental`

Any idea what that might be about?

**Comment by et** [comment]
Pretty sure it's related to [this](https://github.com/jprichardson/node-fs-extra/issues/577).

**Comment by sindresorhus** [comment]
This has been fixed in Node: https://github.com/nodejs/node/commit/2271234af457f2b3f9009af1c3f2c3128cdeef40

**Comment by et** [comment]
For those visiting here from google. The commit linked is included in node v10.2.0
