### ISSUE TITLE
Running on files on an external drive, the files sometimes don't appear in Trash until a file is manually deleted

### ISSUE THREAD

**Issue by garyking** [sindresorhus/trash#83]
Run `trash` on files that are on an external drive. Sometimes, the files don't appear in the Mac trash, until I manually delete a file from the same external drive. Then they all appear at once.

This happens maybe 10% of the time, strangely enough.

**Comment by sindresorhus** [comment]
This sounds like a macOS bug. We're just [calling the system API](https://github.com/sindresorhus/macos-trash/blob/f85ae972e0a041e5f9a461a79db9265e8535234d/Sources/trash/main.swift#L13) to move stuff to the trash.

To do anything more with this report, we'll need a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests).
