### ISSUE TITLE
zsh: command not found: trash 

### ISSUE THREAD

**Issue by jpullman4** [sindresorhus/trash#84]
I am using oh my zsh on Mac OS and ran into the Youtube comment below that found a solution to the same issue that I am having. I was able to verify usr/local/.npm-global. The comment reads as follows: 

"The problem was that my npm global path prefix was set to usr/local/.npm-global as opposed to the typical default path of usr/local. This results in the trash executable not being added to your usr/local/bin. You have to reset your path in your bash or zsh profile to what the default is (Google it) and then source your zsh or bash profile again."

I am new to this command line stuff and get lost at: "You have to reset your path in your bash or zsh profile to what the default is". Could you please be more specific on how I do this (what to type in and where)? 

The first two lines in my .zshrc file are (commented out):
If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

Do I need to uncomment and modify the second line? If so, what modification needs to my made?
Thanks

**Comment by jpullman4** [comment]
Nevermind - SOLVED following these instructions:https://mrmadhat.com/terminal/unable-use-globally-installed-npm-modules-switching-zsh/

**Comment by shaktiness** [comment]
I've tried installing trash in many ways it's not working. I'm getting this big laundry list of things when I do: 
$ npm install trash
npm install trash deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN mini-create-react-context@0.3.2 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-calendar@2.19.2 requires a peer of react@>=15.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-calendar@2.19.2 requires a peer of react-dom@>=15.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-date-picker@7.10.0 requires a peer of react@>=15.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-date-picker@7.10.0 requires a peer of react-dom@>=15.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-fit@1.2.0 requires a peer of react@>=15.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-fit@1.2.0 requires a peer of react-dom@>=15.5 but none is installed. You must install peer dependencies yourself.
npm WARN react-router@5.1.2 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-dom@5.1.2 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN chris@1.0.0 No description
npm WARN chris@1.0.0 No repository field.

+ trash@6.1.1
updated 1 package and audited 310 packages in 8.606s

2 packages are looking for funding
  run `npm fund` for details
